### ISSUE TITLE
Unsure??

### ISSUE THREAD

**Issue by Breeto93** [sgruendel/alexa-garmin-connect-status#1]
Hi, I have activated this 'skill' on Alexa, but confused what is its purpose? is it simply to check Garmins status for different syncs etc or is it to enable me to access eg how many steps ive taken today? Cheers, Paul

**Comment by sgruendel** [comment]
Hi Paul, yes it just checks the overall status page https://connect.garmin.com/status/. Unfortunately, authentication needed to query your data like step count, last workout etc. is not working right now, but I'll try to come up with something.

**Comment by Breeto93** [comment]
Cool idea, thanks mate

Sent from Mail for Windows 10
